version: '3.8'

services:
  db:
    image: mysql:8.0.33
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: bakop
      MYSQL_PASSWORD: bakop

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: bakop
      WORDPRESS_DB_PASSWORD: bakop
    volumes:
      - ./themes:/var/www/html/wp-content/themes

volumes:
  db_data: